arii_Blockly_index:
    pattern:  /
    defaults: { _controller: AriiBlocklyBundle:Default:index }

arii_Blockly_readme:
    pattern:  /readme
    defaults: { _controller: AriiBlocklyBundle:Default:readme }

json_Blockly_ribbon:
    pattern:  /ribbon.json
    defaults: { _controller: AriiBlocklyBundle:Default:ribbon }

xml_Blockly_toolbar:
    pattern:  /toolbar.xml
    defaults: { _controller: AriiBlocklyBundle:Default:toolbar }

xml_Blockly_list:
    pattern:  /list.xml
    defaults: { _controller: AriiBlocklyBundle:Default:list }

xml_Blockly_get:
    pattern:  /get.xml
    defaults: { _controller: AriiBlocklyBundle:Default:get }

arii_Blockly_save:
    pattern:  /save
    defaults: { _controller: AriiBlocklyBundle:Default:save }

arii_Blockly_generate:
    pattern:  /generate
    defaults: { _controller: AriiBlocklyBundle:Default:generate }

# Deploy
arii_Blockly_edit:
    pattern:  /edit
    defaults: { _controller: AriiBlocklyBundle:Default:edit }

# CHECK 

arii_Blockly_check:
    pattern:  /check
    defaults: { _controller: AriiBlocklyBundle:Default:check }

xml_Blockly_toolbar_check:
    pattern:  /toolbar_check.xml
    defaults: { _controller: AriiBlocklyBundle:Default:toolbar_check }

# Scripts
arii_Blockly_scripts:
    pattern:  /scripts
    defaults: { _controller: AriiBlocklyBundle:Scripts:index }

xml_Blockly_scripts_list:
    pattern:  /scripts/list.xml
    defaults: { _controller: AriiBlocklyBundle:Scripts:list }
    
# Deploy
arii_Blockly_deploy:
    pattern:  /deploy
    defaults: { _controller: AriiBlocklyBundle:Default:deploy }
