services:
#    arii_blockly.example:
#        class: Arii\BlocklyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    blockly_generate.autosys:
        class: Arii\BlocklyBundle\Service\GenerateAutosys
        arguments: [ ]
