services:
#    arii_blockly.example:
#        class: Arii\BlocklyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    arii_blockly.jobscheduler:
        class: Arii\BlocklyBundle\Service\JobScheduler
        arguments: [ "%kernel.root_dir%", %arii_blockly% ]
